language: node_js

node_js:
  - 'lts/*'
  - 'stable'

before_script: npm i -D webpack jsdom

script: npm t

after_success: npm i -D coveralls && cat ./coverage/lcov.info | node_modules/.bin/coveralls

notifications:
  email: false
